---
title: "Packages"
output: 
  html_document:
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R {-}

Install R, and Rstudio

# Packages {-}


## From CRAN {-}

These can be installed directly using install.packages()

__ggplot2__: For plotting data ggplot2 is very useful - can be installed from CRAN

__ggpubr__: For modifying ggplot2 plots to be even more informative

__ggrepel__, __ggnetwork__ and __pheatmap__: additional plotting tools

__tidyverse__: A collection of general data handling tools gaining much popularity within the R user community

__broom__: A tidyverse add-on making it easy to compute the same type of model across subsets of data and/or several response variables

__picante__: Phylogenetic integration in analysis

__ape__: For handling phylogenetic trees this package is good. 

__vegan__: Vegan is a very useful package with a lot of functionality. However, here we use only the adonis() function. 

__phyloseqGraphTest__ and __compositions__: Specific tools microbiome data

__readr__, __glue__, __reshape2__,  __DT__, __lsmeans__, and __devtools__: additional tools for making life easier. 

__BiocManager__: A package to install things from Bioconductor 

## From Bioconductor {-}

These can be installed using the BiocManager package: BiocManager::install()

__phyloseq__: There are several packages for handling microbiome type data. For this course we use phyloseq see [tutorial](https://joey711.github.io/phyloseq/tutorials-index.html)

__DESeq2__: This package is developed for _Differential Expression_ statistics for RNA-seq data. However, it is widely used for microbiome data as well. 

__metagenomeSeq__: Is a package for handling microbiome data. Here, especially the differential abundance testing procedure featureModel() is used. 

__limma__: A general package for multiple _Differential Expression_ stats developed for RNA-seq. 

__variancePartition__ and __edgeR__: As limma, but makign mixed models doable, for instance from longitudinal / repeated measures experiments.

__ggtree__: A nice vizualisation package for plotting tree, build on top of ggplot2 functionality.

__BiocParallel__: Getting stuff to run quicker. 

__vsn__: Normalizing toolbox ported from Microarray data analysis. 

## From Github {-}

These can be installed using the packages devtools or remotes (both available on CRAN) usign devtools::install_github() or remotes::install_github()

__metagMisc__: A package with functionallity for cross-talk between different packages found on [github](https://rdrr.io/github/vmikk/metagMisc/)

__DAtest__: This a custome made _single purpose_ package to be found on [github](https://github.com/Russel88/DAtest)

__qiime2R__: Package for porting between QIIME (python environment) and R. Can be installed by devtools::install_github("jbisanz/qiime2R"). 

For details on installation and getting-started, please check vignettes, help-documentation, google, youtube,....  Most things are pretty easy to copy-paste and run from examples and then exchange with your own data. 
